//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CliniSafePhoneAppServiceReference
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://clinisafe.com/phoneapp", ConfigurationName="CliniSafePhoneAppServiceReference.PhoneAppSoap")]
    public interface PhoneAppSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://clinisafe.com/phoneapp/HelloWorld", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string HelloWorld();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://clinisafe.com/phoneapp/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<string> HelloWorldAsync();
        
        // CODEGEN: Generating message contract since message HandshakeRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://clinisafe.com/phoneapp/Handshake", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CliniSafePhoneAppServiceReference.HandshakeResponse Handshake(CliniSafePhoneAppServiceReference.HandshakeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://clinisafe.com/phoneapp/Handshake", ReplyAction="*")]
        System.Threading.Tasks.Task<CliniSafePhoneAppServiceReference.HandshakeResponse> HandshakeAsync(CliniSafePhoneAppServiceReference.HandshakeRequest request);
        
        // CODEGEN: Generating message contract since message AuthenticateRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://clinisafe.com/phoneapp/Authenticate", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CliniSafePhoneAppServiceReference.AuthenticateResponse Authenticate(CliniSafePhoneAppServiceReference.AuthenticateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://clinisafe.com/phoneapp/Authenticate", ReplyAction="*")]
        System.Threading.Tasks.Task<CliniSafePhoneAppServiceReference.AuthenticateResponse> AuthenticateAsync(CliniSafePhoneAppServiceReference.AuthenticateRequest request);
        
        // CODEGEN: Generating message contract since message GetProjectsForUserRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://clinisafe.com/phoneapp/GetProjectsForUser", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CliniSafePhoneAppServiceReference.GetProjectsForUserResponse GetProjectsForUser(CliniSafePhoneAppServiceReference.GetProjectsForUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://clinisafe.com/phoneapp/GetProjectsForUser", ReplyAction="*")]
        System.Threading.Tasks.Task<CliniSafePhoneAppServiceReference.GetProjectsForUserResponse> GetProjectsForUserAsync(CliniSafePhoneAppServiceReference.GetProjectsForUserRequest request);
        
        // CODEGEN: Generating message contract since message GetCountriesForProjectForMonitorUserRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://clinisafe.com/phoneapp/GetCountriesForProjectForMonitorUser", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CliniSafePhoneAppServiceReference.GetCountriesForProjectForMonitorUserResponse GetCountriesForProjectForMonitorUser(CliniSafePhoneAppServiceReference.GetCountriesForProjectForMonitorUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://clinisafe.com/phoneapp/GetCountriesForProjectForMonitorUser", ReplyAction="*")]
        System.Threading.Tasks.Task<CliniSafePhoneAppServiceReference.GetCountriesForProjectForMonitorUserResponse> GetCountriesForProjectForMonitorUserAsync(CliniSafePhoneAppServiceReference.GetCountriesForProjectForMonitorUserRequest request);
        
        // CODEGEN: Generating message contract since message GetResearchSitesForProjectForInvestigtorUserRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://clinisafe.com/phoneapp/GetResearchSitesForProjectForInvestigtorUser", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CliniSafePhoneAppServiceReference.GetResearchSitesForProjectForInvestigtorUserResponse GetResearchSitesForProjectForInvestigtorUser(CliniSafePhoneAppServiceReference.GetResearchSitesForProjectForInvestigtorUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://clinisafe.com/phoneapp/GetResearchSitesForProjectForInvestigtorUser", ReplyAction="*")]
        System.Threading.Tasks.Task<CliniSafePhoneAppServiceReference.GetResearchSitesForProjectForInvestigtorUserResponse> GetResearchSitesForProjectForInvestigtorUserAsync(CliniSafePhoneAppServiceReference.GetResearchSitesForProjectForInvestigtorUserRequest request);
        
        // CODEGEN: Generating message contract since message CheckTrialStatusRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://clinisafe.com/phoneapp/CheckTrialStatus", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CliniSafePhoneAppServiceReference.CheckTrialStatusResponse CheckTrialStatus(CliniSafePhoneAppServiceReference.CheckTrialStatusRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://clinisafe.com/phoneapp/CheckTrialStatus", ReplyAction="*")]
        System.Threading.Tasks.Task<CliniSafePhoneAppServiceReference.CheckTrialStatusResponse> CheckTrialStatusAsync(CliniSafePhoneAppServiceReference.CheckTrialStatusRequest request);
        
        // CODEGEN: Generating message contract since message GetTrailDetailsRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://clinisafe.com/phoneapp/GetTrailDetails", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CliniSafePhoneAppServiceReference.GetTrailDetailsResponse GetTrailDetails(CliniSafePhoneAppServiceReference.GetTrailDetailsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://clinisafe.com/phoneapp/GetTrailDetails", ReplyAction="*")]
        System.Threading.Tasks.Task<CliniSafePhoneAppServiceReference.GetTrailDetailsResponse> GetTrailDetailsAsync(CliniSafePhoneAppServiceReference.GetTrailDetailsRequest request);
        
        // CODEGEN: Generating message contract since message CheckGenericDrugNameRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://clinisafe.com/phoneapp/CheckGenericDrugName", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CliniSafePhoneAppServiceReference.CheckGenericDrugNameResponse CheckGenericDrugName(CliniSafePhoneAppServiceReference.CheckGenericDrugNameRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://clinisafe.com/phoneapp/CheckGenericDrugName", ReplyAction="*")]
        System.Threading.Tasks.Task<CliniSafePhoneAppServiceReference.CheckGenericDrugNameResponse> CheckGenericDrugNameAsync(CliniSafePhoneAppServiceReference.CheckGenericDrugNameRequest request);
        
        // CODEGEN: Generating message contract since message FindGenericDrugNameRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://clinisafe.com/phoneapp/FindGenericDrugName", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CliniSafePhoneAppServiceReference.FindGenericDrugNameResponse FindGenericDrugName(CliniSafePhoneAppServiceReference.FindGenericDrugNameRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://clinisafe.com/phoneapp/FindGenericDrugName", ReplyAction="*")]
        System.Threading.Tasks.Task<CliniSafePhoneAppServiceReference.FindGenericDrugNameResponse> FindGenericDrugNameAsync(CliniSafePhoneAppServiceReference.FindGenericDrugNameRequest request);
        
        // CODEGEN: Generating message contract since message CheckGenericDrugNamesRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://clinisafe.com/phoneapp/CheckGenericDrugNames", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CliniSafePhoneAppServiceReference.CheckGenericDrugNamesResponse CheckGenericDrugNames(CliniSafePhoneAppServiceReference.CheckGenericDrugNamesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://clinisafe.com/phoneapp/CheckGenericDrugNames", ReplyAction="*")]
        System.Threading.Tasks.Task<CliniSafePhoneAppServiceReference.CheckGenericDrugNamesResponse> CheckGenericDrugNamesAsync(CliniSafePhoneAppServiceReference.CheckGenericDrugNamesRequest request);
        
        // CODEGEN: Generating message contract since message GetQuestionsRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://clinisafe.com/phoneapp/GetQuestions", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CliniSafePhoneAppServiceReference.GetQuestionsResponse GetQuestions(CliniSafePhoneAppServiceReference.GetQuestionsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://clinisafe.com/phoneapp/GetQuestions", ReplyAction="*")]
        System.Threading.Tasks.Task<CliniSafePhoneAppServiceReference.GetQuestionsResponse> GetQuestionsAsync(CliniSafePhoneAppServiceReference.GetQuestionsRequest request);
        
        // CODEGEN: Generating message contract since message ValidateDrugsRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://clinisafe.com/phoneapp/ValidateDrugs", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CliniSafePhoneAppServiceReference.ValidateDrugsResponse ValidateDrugs(CliniSafePhoneAppServiceReference.ValidateDrugsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://clinisafe.com/phoneapp/ValidateDrugs", ReplyAction="*")]
        System.Threading.Tasks.Task<CliniSafePhoneAppServiceReference.ValidateDrugsResponse> ValidateDrugsAsync(CliniSafePhoneAppServiceReference.ValidateDrugsRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://clinisafe.com/phoneapp")]
    public partial class HandshakeHeader
    {
        
        private string cPAVersionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string CPAVersion
        {
            get
            {
                return this.cPAVersionField;
            }
            set
            {
                this.cPAVersionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://clinisafe.com/phoneapp")]
    public partial class ValidateDrugsOutputs
    {
        
        private string hTMLResultField;
        
        private string xMLResultField;
        
        private string xMLDrugRuleMessagesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string HTMLResult
        {
            get
            {
                return this.hTMLResultField;
            }
            set
            {
                this.hTMLResultField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string XMLResult
        {
            get
            {
                return this.xMLResultField;
            }
            set
            {
                this.xMLResultField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string XMLDrugRuleMessages
        {
            get
            {
                return this.xMLDrugRuleMessagesField;
            }
            set
            {
                this.xMLDrugRuleMessagesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://clinisafe.com/phoneapp")]
    public partial class ValidateDrugsInputs
    {
        
        private string drugNamesField;
        
        private string questionsAndAnswersField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string DrugNames
        {
            get
            {
                return this.drugNamesField;
            }
            set
            {
                this.drugNamesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string QuestionsAndAnswers
        {
            get
            {
                return this.questionsAndAnswersField;
            }
            set
            {
                this.questionsAndAnswersField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://clinisafe.com/phoneapp")]
    public partial class GetTrialDetailsOutput
    {
        
        private string shortTitleField;
        
        private string fullTitleField;
        
        private string countryField;
        
        private string languageField;
        
        private string userMessageField;
        
        private string statusField;
        
        private bool hasQuestionsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ShortTitle
        {
            get
            {
                return this.shortTitleField;
            }
            set
            {
                this.shortTitleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string FullTitle
        {
            get
            {
                return this.fullTitleField;
            }
            set
            {
                this.fullTitleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Country
        {
            get
            {
                return this.countryField;
            }
            set
            {
                this.countryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Language
        {
            get
            {
                return this.languageField;
            }
            set
            {
                this.languageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string UserMessage
        {
            get
            {
                return this.userMessageField;
            }
            set
            {
                this.userMessageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public bool HasQuestions
        {
            get
            {
                return this.hasQuestionsField;
            }
            set
            {
                this.hasQuestionsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://clinisafe.com/phoneapp")]
    public partial class AuthHeader
    {
        
        private string usernameField;
        
        private string passwordField;
        
        private string cPAVersionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Username
        {
            get
            {
                return this.usernameField;
            }
            set
            {
                this.usernameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Password
        {
            get
            {
                return this.passwordField;
            }
            set
            {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string CPAVersion
        {
            get
            {
                return this.cPAVersionField;
            }
            set
            {
                this.cPAVersionField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Handshake", WrapperNamespace="http://clinisafe.com/phoneapp", IsWrapped=true)]
    public partial class HandshakeRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://clinisafe.com/phoneapp")]
        public CliniSafePhoneAppServiceReference.HandshakeHeader HandshakeHeader;
        
        public HandshakeRequest()
        {
        }
        
        public HandshakeRequest(CliniSafePhoneAppServiceReference.HandshakeHeader HandshakeHeader)
        {
            this.HandshakeHeader = HandshakeHeader;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="HandshakeResponse", WrapperNamespace="http://clinisafe.com/phoneapp", IsWrapped=true)]
    public partial class HandshakeResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://clinisafe.com/phoneapp", Order=0)]
        public string HandshakeResult;
        
        public HandshakeResponse()
        {
        }
        
        public HandshakeResponse(string HandshakeResult)
        {
            this.HandshakeResult = HandshakeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Authenticate", WrapperNamespace="http://clinisafe.com/phoneapp", IsWrapped=true)]
    public partial class AuthenticateRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://clinisafe.com/phoneapp")]
        public CliniSafePhoneAppServiceReference.AuthHeader AuthHeader;
        
        public AuthenticateRequest()
        {
        }
        
        public AuthenticateRequest(CliniSafePhoneAppServiceReference.AuthHeader AuthHeader)
        {
            this.AuthHeader = AuthHeader;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AuthenticateResponse", WrapperNamespace="http://clinisafe.com/phoneapp", IsWrapped=true)]
    public partial class AuthenticateResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://clinisafe.com/phoneapp", Order=0)]
        public string AuthenticateResult;
        
        public AuthenticateResponse()
        {
        }
        
        public AuthenticateResponse(string AuthenticateResult)
        {
            this.AuthenticateResult = AuthenticateResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetProjectsForUser", WrapperNamespace="http://clinisafe.com/phoneapp", IsWrapped=true)]
    public partial class GetProjectsForUserRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://clinisafe.com/phoneapp")]
        public CliniSafePhoneAppServiceReference.AuthHeader AuthHeader;
        
        public GetProjectsForUserRequest()
        {
        }
        
        public GetProjectsForUserRequest(CliniSafePhoneAppServiceReference.AuthHeader AuthHeader)
        {
            this.AuthHeader = AuthHeader;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetProjectsForUserResponse", WrapperNamespace="http://clinisafe.com/phoneapp", IsWrapped=true)]
    public partial class GetProjectsForUserResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://clinisafe.com/phoneapp", Order=0)]
        public string GetProjectsForUserResult;
        
        public GetProjectsForUserResponse()
        {
        }
        
        public GetProjectsForUserResponse(string GetProjectsForUserResult)
        {
            this.GetProjectsForUserResult = GetProjectsForUserResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCountriesForProjectForMonitorUser", WrapperNamespace="http://clinisafe.com/phoneapp", IsWrapped=true)]
    public partial class GetCountriesForProjectForMonitorUserRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://clinisafe.com/phoneapp")]
        public CliniSafePhoneAppServiceReference.AuthHeader AuthHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://clinisafe.com/phoneapp", Order=0)]
        public int ProjectID;
        
        public GetCountriesForProjectForMonitorUserRequest()
        {
        }
        
        public GetCountriesForProjectForMonitorUserRequest(CliniSafePhoneAppServiceReference.AuthHeader AuthHeader, int ProjectID)
        {
            this.AuthHeader = AuthHeader;
            this.ProjectID = ProjectID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCountriesForProjectForMonitorUserResponse", WrapperNamespace="http://clinisafe.com/phoneapp", IsWrapped=true)]
    public partial class GetCountriesForProjectForMonitorUserResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://clinisafe.com/phoneapp", Order=0)]
        public string GetCountriesForProjectForMonitorUserResult;
        
        public GetCountriesForProjectForMonitorUserResponse()
        {
        }
        
        public GetCountriesForProjectForMonitorUserResponse(string GetCountriesForProjectForMonitorUserResult)
        {
            this.GetCountriesForProjectForMonitorUserResult = GetCountriesForProjectForMonitorUserResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetResearchSitesForProjectForInvestigtorUser", WrapperNamespace="http://clinisafe.com/phoneapp", IsWrapped=true)]
    public partial class GetResearchSitesForProjectForInvestigtorUserRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://clinisafe.com/phoneapp")]
        public CliniSafePhoneAppServiceReference.AuthHeader AuthHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://clinisafe.com/phoneapp", Order=0)]
        public int ProjectID;
        
        public GetResearchSitesForProjectForInvestigtorUserRequest()
        {
        }
        
        public GetResearchSitesForProjectForInvestigtorUserRequest(CliniSafePhoneAppServiceReference.AuthHeader AuthHeader, int ProjectID)
        {
            this.AuthHeader = AuthHeader;
            this.ProjectID = ProjectID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetResearchSitesForProjectForInvestigtorUserResponse", WrapperNamespace="http://clinisafe.com/phoneapp", IsWrapped=true)]
    public partial class GetResearchSitesForProjectForInvestigtorUserResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://clinisafe.com/phoneapp", Order=0)]
        public string GetResearchSitesForProjectForInvestigtorUserResult;
        
        public GetResearchSitesForProjectForInvestigtorUserResponse()
        {
        }
        
        public GetResearchSitesForProjectForInvestigtorUserResponse(string GetResearchSitesForProjectForInvestigtorUserResult)
        {
            this.GetResearchSitesForProjectForInvestigtorUserResult = GetResearchSitesForProjectForInvestigtorUserResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CheckTrialStatus", WrapperNamespace="http://clinisafe.com/phoneapp", IsWrapped=true)]
    public partial class CheckTrialStatusRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://clinisafe.com/phoneapp")]
        public CliniSafePhoneAppServiceReference.AuthHeader AuthHeader;
        
        public CheckTrialStatusRequest()
        {
        }
        
        public CheckTrialStatusRequest(CliniSafePhoneAppServiceReference.AuthHeader AuthHeader)
        {
            this.AuthHeader = AuthHeader;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CheckTrialStatusResponse", WrapperNamespace="http://clinisafe.com/phoneapp", IsWrapped=true)]
    public partial class CheckTrialStatusResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://clinisafe.com/phoneapp", Order=0)]
        public string CheckTrialStatusResult;
        
        public CheckTrialStatusResponse()
        {
        }
        
        public CheckTrialStatusResponse(string CheckTrialStatusResult)
        {
            this.CheckTrialStatusResult = CheckTrialStatusResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetTrailDetails", WrapperNamespace="http://clinisafe.com/phoneapp", IsWrapped=true)]
    public partial class GetTrailDetailsRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://clinisafe.com/phoneapp")]
        public CliniSafePhoneAppServiceReference.AuthHeader AuthHeader;
        
        public GetTrailDetailsRequest()
        {
        }
        
        public GetTrailDetailsRequest(CliniSafePhoneAppServiceReference.AuthHeader AuthHeader)
        {
            this.AuthHeader = AuthHeader;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetTrailDetailsResponse", WrapperNamespace="http://clinisafe.com/phoneapp", IsWrapped=true)]
    public partial class GetTrailDetailsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://clinisafe.com/phoneapp", Order=0)]
        public CliniSafePhoneAppServiceReference.GetTrialDetailsOutput GetTrailDetailsResult;
        
        public GetTrailDetailsResponse()
        {
        }
        
        public GetTrailDetailsResponse(CliniSafePhoneAppServiceReference.GetTrialDetailsOutput GetTrailDetailsResult)
        {
            this.GetTrailDetailsResult = GetTrailDetailsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CheckGenericDrugName", WrapperNamespace="http://clinisafe.com/phoneapp", IsWrapped=true)]
    public partial class CheckGenericDrugNameRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://clinisafe.com/phoneapp")]
        public CliniSafePhoneAppServiceReference.AuthHeader AuthHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://clinisafe.com/phoneapp", Order=0)]
        public string GenericDrugName;
        
        public CheckGenericDrugNameRequest()
        {
        }
        
        public CheckGenericDrugNameRequest(CliniSafePhoneAppServiceReference.AuthHeader AuthHeader, string GenericDrugName)
        {
            this.AuthHeader = AuthHeader;
            this.GenericDrugName = GenericDrugName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CheckGenericDrugNameResponse", WrapperNamespace="http://clinisafe.com/phoneapp", IsWrapped=true)]
    public partial class CheckGenericDrugNameResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://clinisafe.com/phoneapp", Order=0)]
        public bool CheckGenericDrugNameResult;
        
        public CheckGenericDrugNameResponse()
        {
        }
        
        public CheckGenericDrugNameResponse(bool CheckGenericDrugNameResult)
        {
            this.CheckGenericDrugNameResult = CheckGenericDrugNameResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FindGenericDrugName", WrapperNamespace="http://clinisafe.com/phoneapp", IsWrapped=true)]
    public partial class FindGenericDrugNameRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://clinisafe.com/phoneapp")]
        public CliniSafePhoneAppServiceReference.AuthHeader AuthHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://clinisafe.com/phoneapp", Order=0)]
        public string GenericDrugNameToFind;
        
        public FindGenericDrugNameRequest()
        {
        }
        
        public FindGenericDrugNameRequest(CliniSafePhoneAppServiceReference.AuthHeader AuthHeader, string GenericDrugNameToFind)
        {
            this.AuthHeader = AuthHeader;
            this.GenericDrugNameToFind = GenericDrugNameToFind;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FindGenericDrugNameResponse", WrapperNamespace="http://clinisafe.com/phoneapp", IsWrapped=true)]
    public partial class FindGenericDrugNameResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://clinisafe.com/phoneapp", Order=0)]
        public string FindGenericDrugNameResult;
        
        public FindGenericDrugNameResponse()
        {
        }
        
        public FindGenericDrugNameResponse(string FindGenericDrugNameResult)
        {
            this.FindGenericDrugNameResult = FindGenericDrugNameResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CheckGenericDrugNames", WrapperNamespace="http://clinisafe.com/phoneapp", IsWrapped=true)]
    public partial class CheckGenericDrugNamesRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://clinisafe.com/phoneapp")]
        public CliniSafePhoneAppServiceReference.AuthHeader AuthHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://clinisafe.com/phoneapp", Order=0)]
        public string DrugsToTest;
        
        public CheckGenericDrugNamesRequest()
        {
        }
        
        public CheckGenericDrugNamesRequest(CliniSafePhoneAppServiceReference.AuthHeader AuthHeader, string DrugsToTest)
        {
            this.AuthHeader = AuthHeader;
            this.DrugsToTest = DrugsToTest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CheckGenericDrugNamesResponse", WrapperNamespace="http://clinisafe.com/phoneapp", IsWrapped=true)]
    public partial class CheckGenericDrugNamesResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://clinisafe.com/phoneapp", Order=0)]
        public string CheckGenericDrugNamesResult;
        
        public CheckGenericDrugNamesResponse()
        {
        }
        
        public CheckGenericDrugNamesResponse(string CheckGenericDrugNamesResult)
        {
            this.CheckGenericDrugNamesResult = CheckGenericDrugNamesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetQuestions", WrapperNamespace="http://clinisafe.com/phoneapp", IsWrapped=true)]
    public partial class GetQuestionsRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://clinisafe.com/phoneapp")]
        public CliniSafePhoneAppServiceReference.AuthHeader AuthHeader;
        
        public GetQuestionsRequest()
        {
        }
        
        public GetQuestionsRequest(CliniSafePhoneAppServiceReference.AuthHeader AuthHeader)
        {
            this.AuthHeader = AuthHeader;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetQuestionsResponse", WrapperNamespace="http://clinisafe.com/phoneapp", IsWrapped=true)]
    public partial class GetQuestionsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://clinisafe.com/phoneapp", Order=0)]
        public string GetQuestionsResult;
        
        public GetQuestionsResponse()
        {
        }
        
        public GetQuestionsResponse(string GetQuestionsResult)
        {
            this.GetQuestionsResult = GetQuestionsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ValidateDrugs", WrapperNamespace="http://clinisafe.com/phoneapp", IsWrapped=true)]
    public partial class ValidateDrugsRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://clinisafe.com/phoneapp")]
        public CliniSafePhoneAppServiceReference.AuthHeader AuthHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://clinisafe.com/phoneapp", Order=0)]
        public CliniSafePhoneAppServiceReference.ValidateDrugsInputs DrugValidatorInputs;
        
        public ValidateDrugsRequest()
        {
        }
        
        public ValidateDrugsRequest(CliniSafePhoneAppServiceReference.AuthHeader AuthHeader, CliniSafePhoneAppServiceReference.ValidateDrugsInputs DrugValidatorInputs)
        {
            this.AuthHeader = AuthHeader;
            this.DrugValidatorInputs = DrugValidatorInputs;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ValidateDrugsResponse", WrapperNamespace="http://clinisafe.com/phoneapp", IsWrapped=true)]
    public partial class ValidateDrugsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://clinisafe.com/phoneapp", Order=0)]
        public CliniSafePhoneAppServiceReference.ValidateDrugsOutputs ValidateDrugsResult;
        
        public ValidateDrugsResponse()
        {
        }
        
        public ValidateDrugsResponse(CliniSafePhoneAppServiceReference.ValidateDrugsOutputs ValidateDrugsResult)
        {
            this.ValidateDrugsResult = ValidateDrugsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    public interface PhoneAppSoapChannel : CliniSafePhoneAppServiceReference.PhoneAppSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    public partial class PhoneAppSoapClient : System.ServiceModel.ClientBase<CliniSafePhoneAppServiceReference.PhoneAppSoap>, CliniSafePhoneAppServiceReference.PhoneAppSoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public PhoneAppSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(PhoneAppSoapClient.GetBindingForEndpoint(endpointConfiguration), PhoneAppSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PhoneAppSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(PhoneAppSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PhoneAppSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(PhoneAppSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PhoneAppSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public string HelloWorld()
        {
            return base.Channel.HelloWorld();
        }
        
        public System.Threading.Tasks.Task<string> HelloWorldAsync()
        {
            return base.Channel.HelloWorldAsync();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CliniSafePhoneAppServiceReference.HandshakeResponse CliniSafePhoneAppServiceReference.PhoneAppSoap.Handshake(CliniSafePhoneAppServiceReference.HandshakeRequest request)
        {
            return base.Channel.Handshake(request);
        }
        
        public string Handshake(CliniSafePhoneAppServiceReference.HandshakeHeader HandshakeHeader)
        {
            CliniSafePhoneAppServiceReference.HandshakeRequest inValue = new CliniSafePhoneAppServiceReference.HandshakeRequest();
            inValue.HandshakeHeader = HandshakeHeader;
            CliniSafePhoneAppServiceReference.HandshakeResponse retVal = ((CliniSafePhoneAppServiceReference.PhoneAppSoap)(this)).Handshake(inValue);
            return retVal.HandshakeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CliniSafePhoneAppServiceReference.HandshakeResponse> CliniSafePhoneAppServiceReference.PhoneAppSoap.HandshakeAsync(CliniSafePhoneAppServiceReference.HandshakeRequest request)
        {
            return base.Channel.HandshakeAsync(request);
        }
        
        public System.Threading.Tasks.Task<CliniSafePhoneAppServiceReference.HandshakeResponse> HandshakeAsync(CliniSafePhoneAppServiceReference.HandshakeHeader HandshakeHeader)
        {
            CliniSafePhoneAppServiceReference.HandshakeRequest inValue = new CliniSafePhoneAppServiceReference.HandshakeRequest();
            inValue.HandshakeHeader = HandshakeHeader;
            return ((CliniSafePhoneAppServiceReference.PhoneAppSoap)(this)).HandshakeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CliniSafePhoneAppServiceReference.AuthenticateResponse CliniSafePhoneAppServiceReference.PhoneAppSoap.Authenticate(CliniSafePhoneAppServiceReference.AuthenticateRequest request)
        {
            return base.Channel.Authenticate(request);
        }
        
        public string Authenticate(CliniSafePhoneAppServiceReference.AuthHeader AuthHeader)
        {
            CliniSafePhoneAppServiceReference.AuthenticateRequest inValue = new CliniSafePhoneAppServiceReference.AuthenticateRequest();
            inValue.AuthHeader = AuthHeader;
            CliniSafePhoneAppServiceReference.AuthenticateResponse retVal = ((CliniSafePhoneAppServiceReference.PhoneAppSoap)(this)).Authenticate(inValue);
            return retVal.AuthenticateResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CliniSafePhoneAppServiceReference.AuthenticateResponse> CliniSafePhoneAppServiceReference.PhoneAppSoap.AuthenticateAsync(CliniSafePhoneAppServiceReference.AuthenticateRequest request)
        {
            return base.Channel.AuthenticateAsync(request);
        }
        
        public System.Threading.Tasks.Task<CliniSafePhoneAppServiceReference.AuthenticateResponse> AuthenticateAsync(CliniSafePhoneAppServiceReference.AuthHeader AuthHeader)
        {
            CliniSafePhoneAppServiceReference.AuthenticateRequest inValue = new CliniSafePhoneAppServiceReference.AuthenticateRequest();
            inValue.AuthHeader = AuthHeader;
            return ((CliniSafePhoneAppServiceReference.PhoneAppSoap)(this)).AuthenticateAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CliniSafePhoneAppServiceReference.GetProjectsForUserResponse CliniSafePhoneAppServiceReference.PhoneAppSoap.GetProjectsForUser(CliniSafePhoneAppServiceReference.GetProjectsForUserRequest request)
        {
            return base.Channel.GetProjectsForUser(request);
        }
        
        public string GetProjectsForUser(CliniSafePhoneAppServiceReference.AuthHeader AuthHeader)
        {
            CliniSafePhoneAppServiceReference.GetProjectsForUserRequest inValue = new CliniSafePhoneAppServiceReference.GetProjectsForUserRequest();
            inValue.AuthHeader = AuthHeader;
            CliniSafePhoneAppServiceReference.GetProjectsForUserResponse retVal = ((CliniSafePhoneAppServiceReference.PhoneAppSoap)(this)).GetProjectsForUser(inValue);
            return retVal.GetProjectsForUserResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CliniSafePhoneAppServiceReference.GetProjectsForUserResponse> CliniSafePhoneAppServiceReference.PhoneAppSoap.GetProjectsForUserAsync(CliniSafePhoneAppServiceReference.GetProjectsForUserRequest request)
        {
            return base.Channel.GetProjectsForUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<CliniSafePhoneAppServiceReference.GetProjectsForUserResponse> GetProjectsForUserAsync(CliniSafePhoneAppServiceReference.AuthHeader AuthHeader)
        {
            CliniSafePhoneAppServiceReference.GetProjectsForUserRequest inValue = new CliniSafePhoneAppServiceReference.GetProjectsForUserRequest();
            inValue.AuthHeader = AuthHeader;
            return ((CliniSafePhoneAppServiceReference.PhoneAppSoap)(this)).GetProjectsForUserAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CliniSafePhoneAppServiceReference.GetCountriesForProjectForMonitorUserResponse CliniSafePhoneAppServiceReference.PhoneAppSoap.GetCountriesForProjectForMonitorUser(CliniSafePhoneAppServiceReference.GetCountriesForProjectForMonitorUserRequest request)
        {
            return base.Channel.GetCountriesForProjectForMonitorUser(request);
        }
        
        public string GetCountriesForProjectForMonitorUser(CliniSafePhoneAppServiceReference.AuthHeader AuthHeader, int ProjectID)
        {
            CliniSafePhoneAppServiceReference.GetCountriesForProjectForMonitorUserRequest inValue = new CliniSafePhoneAppServiceReference.GetCountriesForProjectForMonitorUserRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.ProjectID = ProjectID;
            CliniSafePhoneAppServiceReference.GetCountriesForProjectForMonitorUserResponse retVal = ((CliniSafePhoneAppServiceReference.PhoneAppSoap)(this)).GetCountriesForProjectForMonitorUser(inValue);
            return retVal.GetCountriesForProjectForMonitorUserResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CliniSafePhoneAppServiceReference.GetCountriesForProjectForMonitorUserResponse> CliniSafePhoneAppServiceReference.PhoneAppSoap.GetCountriesForProjectForMonitorUserAsync(CliniSafePhoneAppServiceReference.GetCountriesForProjectForMonitorUserRequest request)
        {
            return base.Channel.GetCountriesForProjectForMonitorUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<CliniSafePhoneAppServiceReference.GetCountriesForProjectForMonitorUserResponse> GetCountriesForProjectForMonitorUserAsync(CliniSafePhoneAppServiceReference.AuthHeader AuthHeader, int ProjectID)
        {
            CliniSafePhoneAppServiceReference.GetCountriesForProjectForMonitorUserRequest inValue = new CliniSafePhoneAppServiceReference.GetCountriesForProjectForMonitorUserRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.ProjectID = ProjectID;
            return ((CliniSafePhoneAppServiceReference.PhoneAppSoap)(this)).GetCountriesForProjectForMonitorUserAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CliniSafePhoneAppServiceReference.GetResearchSitesForProjectForInvestigtorUserResponse CliniSafePhoneAppServiceReference.PhoneAppSoap.GetResearchSitesForProjectForInvestigtorUser(CliniSafePhoneAppServiceReference.GetResearchSitesForProjectForInvestigtorUserRequest request)
        {
            return base.Channel.GetResearchSitesForProjectForInvestigtorUser(request);
        }
        
        public string GetResearchSitesForProjectForInvestigtorUser(CliniSafePhoneAppServiceReference.AuthHeader AuthHeader, int ProjectID)
        {
            CliniSafePhoneAppServiceReference.GetResearchSitesForProjectForInvestigtorUserRequest inValue = new CliniSafePhoneAppServiceReference.GetResearchSitesForProjectForInvestigtorUserRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.ProjectID = ProjectID;
            CliniSafePhoneAppServiceReference.GetResearchSitesForProjectForInvestigtorUserResponse retVal = ((CliniSafePhoneAppServiceReference.PhoneAppSoap)(this)).GetResearchSitesForProjectForInvestigtorUser(inValue);
            return retVal.GetResearchSitesForProjectForInvestigtorUserResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CliniSafePhoneAppServiceReference.GetResearchSitesForProjectForInvestigtorUserResponse> CliniSafePhoneAppServiceReference.PhoneAppSoap.GetResearchSitesForProjectForInvestigtorUserAsync(CliniSafePhoneAppServiceReference.GetResearchSitesForProjectForInvestigtorUserRequest request)
        {
            return base.Channel.GetResearchSitesForProjectForInvestigtorUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<CliniSafePhoneAppServiceReference.GetResearchSitesForProjectForInvestigtorUserResponse> GetResearchSitesForProjectForInvestigtorUserAsync(CliniSafePhoneAppServiceReference.AuthHeader AuthHeader, int ProjectID)
        {
            CliniSafePhoneAppServiceReference.GetResearchSitesForProjectForInvestigtorUserRequest inValue = new CliniSafePhoneAppServiceReference.GetResearchSitesForProjectForInvestigtorUserRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.ProjectID = ProjectID;
            return ((CliniSafePhoneAppServiceReference.PhoneAppSoap)(this)).GetResearchSitesForProjectForInvestigtorUserAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CliniSafePhoneAppServiceReference.CheckTrialStatusResponse CliniSafePhoneAppServiceReference.PhoneAppSoap.CheckTrialStatus(CliniSafePhoneAppServiceReference.CheckTrialStatusRequest request)
        {
            return base.Channel.CheckTrialStatus(request);
        }
        
        public string CheckTrialStatus(CliniSafePhoneAppServiceReference.AuthHeader AuthHeader)
        {
            CliniSafePhoneAppServiceReference.CheckTrialStatusRequest inValue = new CliniSafePhoneAppServiceReference.CheckTrialStatusRequest();
            inValue.AuthHeader = AuthHeader;
            CliniSafePhoneAppServiceReference.CheckTrialStatusResponse retVal = ((CliniSafePhoneAppServiceReference.PhoneAppSoap)(this)).CheckTrialStatus(inValue);
            return retVal.CheckTrialStatusResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CliniSafePhoneAppServiceReference.CheckTrialStatusResponse> CliniSafePhoneAppServiceReference.PhoneAppSoap.CheckTrialStatusAsync(CliniSafePhoneAppServiceReference.CheckTrialStatusRequest request)
        {
            return base.Channel.CheckTrialStatusAsync(request);
        }
        
        public System.Threading.Tasks.Task<CliniSafePhoneAppServiceReference.CheckTrialStatusResponse> CheckTrialStatusAsync(CliniSafePhoneAppServiceReference.AuthHeader AuthHeader)
        {
            CliniSafePhoneAppServiceReference.CheckTrialStatusRequest inValue = new CliniSafePhoneAppServiceReference.CheckTrialStatusRequest();
            inValue.AuthHeader = AuthHeader;
            return ((CliniSafePhoneAppServiceReference.PhoneAppSoap)(this)).CheckTrialStatusAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CliniSafePhoneAppServiceReference.GetTrailDetailsResponse CliniSafePhoneAppServiceReference.PhoneAppSoap.GetTrailDetails(CliniSafePhoneAppServiceReference.GetTrailDetailsRequest request)
        {
            return base.Channel.GetTrailDetails(request);
        }
        
        public CliniSafePhoneAppServiceReference.GetTrialDetailsOutput GetTrailDetails(CliniSafePhoneAppServiceReference.AuthHeader AuthHeader)
        {
            CliniSafePhoneAppServiceReference.GetTrailDetailsRequest inValue = new CliniSafePhoneAppServiceReference.GetTrailDetailsRequest();
            inValue.AuthHeader = AuthHeader;
            CliniSafePhoneAppServiceReference.GetTrailDetailsResponse retVal = ((CliniSafePhoneAppServiceReference.PhoneAppSoap)(this)).GetTrailDetails(inValue);
            return retVal.GetTrailDetailsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CliniSafePhoneAppServiceReference.GetTrailDetailsResponse> CliniSafePhoneAppServiceReference.PhoneAppSoap.GetTrailDetailsAsync(CliniSafePhoneAppServiceReference.GetTrailDetailsRequest request)
        {
            return base.Channel.GetTrailDetailsAsync(request);
        }
        
        public System.Threading.Tasks.Task<CliniSafePhoneAppServiceReference.GetTrailDetailsResponse> GetTrailDetailsAsync(CliniSafePhoneAppServiceReference.AuthHeader AuthHeader)
        {
            CliniSafePhoneAppServiceReference.GetTrailDetailsRequest inValue = new CliniSafePhoneAppServiceReference.GetTrailDetailsRequest();
            inValue.AuthHeader = AuthHeader;
            return ((CliniSafePhoneAppServiceReference.PhoneAppSoap)(this)).GetTrailDetailsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CliniSafePhoneAppServiceReference.CheckGenericDrugNameResponse CliniSafePhoneAppServiceReference.PhoneAppSoap.CheckGenericDrugName(CliniSafePhoneAppServiceReference.CheckGenericDrugNameRequest request)
        {
            return base.Channel.CheckGenericDrugName(request);
        }
        
        public bool CheckGenericDrugName(CliniSafePhoneAppServiceReference.AuthHeader AuthHeader, string GenericDrugName)
        {
            CliniSafePhoneAppServiceReference.CheckGenericDrugNameRequest inValue = new CliniSafePhoneAppServiceReference.CheckGenericDrugNameRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.GenericDrugName = GenericDrugName;
            CliniSafePhoneAppServiceReference.CheckGenericDrugNameResponse retVal = ((CliniSafePhoneAppServiceReference.PhoneAppSoap)(this)).CheckGenericDrugName(inValue);
            return retVal.CheckGenericDrugNameResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CliniSafePhoneAppServiceReference.CheckGenericDrugNameResponse> CliniSafePhoneAppServiceReference.PhoneAppSoap.CheckGenericDrugNameAsync(CliniSafePhoneAppServiceReference.CheckGenericDrugNameRequest request)
        {
            return base.Channel.CheckGenericDrugNameAsync(request);
        }
        
        public System.Threading.Tasks.Task<CliniSafePhoneAppServiceReference.CheckGenericDrugNameResponse> CheckGenericDrugNameAsync(CliniSafePhoneAppServiceReference.AuthHeader AuthHeader, string GenericDrugName)
        {
            CliniSafePhoneAppServiceReference.CheckGenericDrugNameRequest inValue = new CliniSafePhoneAppServiceReference.CheckGenericDrugNameRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.GenericDrugName = GenericDrugName;
            return ((CliniSafePhoneAppServiceReference.PhoneAppSoap)(this)).CheckGenericDrugNameAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CliniSafePhoneAppServiceReference.FindGenericDrugNameResponse CliniSafePhoneAppServiceReference.PhoneAppSoap.FindGenericDrugName(CliniSafePhoneAppServiceReference.FindGenericDrugNameRequest request)
        {
            return base.Channel.FindGenericDrugName(request);
        }
        
        public string FindGenericDrugName(CliniSafePhoneAppServiceReference.AuthHeader AuthHeader, string GenericDrugNameToFind)
        {
            CliniSafePhoneAppServiceReference.FindGenericDrugNameRequest inValue = new CliniSafePhoneAppServiceReference.FindGenericDrugNameRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.GenericDrugNameToFind = GenericDrugNameToFind;
            CliniSafePhoneAppServiceReference.FindGenericDrugNameResponse retVal = ((CliniSafePhoneAppServiceReference.PhoneAppSoap)(this)).FindGenericDrugName(inValue);
            return retVal.FindGenericDrugNameResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CliniSafePhoneAppServiceReference.FindGenericDrugNameResponse> CliniSafePhoneAppServiceReference.PhoneAppSoap.FindGenericDrugNameAsync(CliniSafePhoneAppServiceReference.FindGenericDrugNameRequest request)
        {
            return base.Channel.FindGenericDrugNameAsync(request);
        }
        
        public System.Threading.Tasks.Task<CliniSafePhoneAppServiceReference.FindGenericDrugNameResponse> FindGenericDrugNameAsync(CliniSafePhoneAppServiceReference.AuthHeader AuthHeader, string GenericDrugNameToFind)
        {
            CliniSafePhoneAppServiceReference.FindGenericDrugNameRequest inValue = new CliniSafePhoneAppServiceReference.FindGenericDrugNameRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.GenericDrugNameToFind = GenericDrugNameToFind;
            return ((CliniSafePhoneAppServiceReference.PhoneAppSoap)(this)).FindGenericDrugNameAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CliniSafePhoneAppServiceReference.CheckGenericDrugNamesResponse CliniSafePhoneAppServiceReference.PhoneAppSoap.CheckGenericDrugNames(CliniSafePhoneAppServiceReference.CheckGenericDrugNamesRequest request)
        {
            return base.Channel.CheckGenericDrugNames(request);
        }
        
        public string CheckGenericDrugNames(CliniSafePhoneAppServiceReference.AuthHeader AuthHeader, string DrugsToTest)
        {
            CliniSafePhoneAppServiceReference.CheckGenericDrugNamesRequest inValue = new CliniSafePhoneAppServiceReference.CheckGenericDrugNamesRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.DrugsToTest = DrugsToTest;
            CliniSafePhoneAppServiceReference.CheckGenericDrugNamesResponse retVal = ((CliniSafePhoneAppServiceReference.PhoneAppSoap)(this)).CheckGenericDrugNames(inValue);
            return retVal.CheckGenericDrugNamesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CliniSafePhoneAppServiceReference.CheckGenericDrugNamesResponse> CliniSafePhoneAppServiceReference.PhoneAppSoap.CheckGenericDrugNamesAsync(CliniSafePhoneAppServiceReference.CheckGenericDrugNamesRequest request)
        {
            return base.Channel.CheckGenericDrugNamesAsync(request);
        }
        
        public System.Threading.Tasks.Task<CliniSafePhoneAppServiceReference.CheckGenericDrugNamesResponse> CheckGenericDrugNamesAsync(CliniSafePhoneAppServiceReference.AuthHeader AuthHeader, string DrugsToTest)
        {
            CliniSafePhoneAppServiceReference.CheckGenericDrugNamesRequest inValue = new CliniSafePhoneAppServiceReference.CheckGenericDrugNamesRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.DrugsToTest = DrugsToTest;
            return ((CliniSafePhoneAppServiceReference.PhoneAppSoap)(this)).CheckGenericDrugNamesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CliniSafePhoneAppServiceReference.GetQuestionsResponse CliniSafePhoneAppServiceReference.PhoneAppSoap.GetQuestions(CliniSafePhoneAppServiceReference.GetQuestionsRequest request)
        {
            return base.Channel.GetQuestions(request);
        }
        
        public string GetQuestions(CliniSafePhoneAppServiceReference.AuthHeader AuthHeader)
        {
            CliniSafePhoneAppServiceReference.GetQuestionsRequest inValue = new CliniSafePhoneAppServiceReference.GetQuestionsRequest();
            inValue.AuthHeader = AuthHeader;
            CliniSafePhoneAppServiceReference.GetQuestionsResponse retVal = ((CliniSafePhoneAppServiceReference.PhoneAppSoap)(this)).GetQuestions(inValue);
            return retVal.GetQuestionsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CliniSafePhoneAppServiceReference.GetQuestionsResponse> CliniSafePhoneAppServiceReference.PhoneAppSoap.GetQuestionsAsync(CliniSafePhoneAppServiceReference.GetQuestionsRequest request)
        {
            return base.Channel.GetQuestionsAsync(request);
        }
        
        public System.Threading.Tasks.Task<CliniSafePhoneAppServiceReference.GetQuestionsResponse> GetQuestionsAsync(CliniSafePhoneAppServiceReference.AuthHeader AuthHeader)
        {
            CliniSafePhoneAppServiceReference.GetQuestionsRequest inValue = new CliniSafePhoneAppServiceReference.GetQuestionsRequest();
            inValue.AuthHeader = AuthHeader;
            return ((CliniSafePhoneAppServiceReference.PhoneAppSoap)(this)).GetQuestionsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CliniSafePhoneAppServiceReference.ValidateDrugsResponse CliniSafePhoneAppServiceReference.PhoneAppSoap.ValidateDrugs(CliniSafePhoneAppServiceReference.ValidateDrugsRequest request)
        {
            return base.Channel.ValidateDrugs(request);
        }
        
        public CliniSafePhoneAppServiceReference.ValidateDrugsOutputs ValidateDrugs(CliniSafePhoneAppServiceReference.AuthHeader AuthHeader, CliniSafePhoneAppServiceReference.ValidateDrugsInputs DrugValidatorInputs)
        {
            CliniSafePhoneAppServiceReference.ValidateDrugsRequest inValue = new CliniSafePhoneAppServiceReference.ValidateDrugsRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.DrugValidatorInputs = DrugValidatorInputs;
            CliniSafePhoneAppServiceReference.ValidateDrugsResponse retVal = ((CliniSafePhoneAppServiceReference.PhoneAppSoap)(this)).ValidateDrugs(inValue);
            return retVal.ValidateDrugsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CliniSafePhoneAppServiceReference.ValidateDrugsResponse> CliniSafePhoneAppServiceReference.PhoneAppSoap.ValidateDrugsAsync(CliniSafePhoneAppServiceReference.ValidateDrugsRequest request)
        {
            return base.Channel.ValidateDrugsAsync(request);
        }
        
        public System.Threading.Tasks.Task<CliniSafePhoneAppServiceReference.ValidateDrugsResponse> ValidateDrugsAsync(CliniSafePhoneAppServiceReference.AuthHeader AuthHeader, CliniSafePhoneAppServiceReference.ValidateDrugsInputs DrugValidatorInputs)
        {
            CliniSafePhoneAppServiceReference.ValidateDrugsRequest inValue = new CliniSafePhoneAppServiceReference.ValidateDrugsRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.DrugValidatorInputs = DrugValidatorInputs;
            return ((CliniSafePhoneAppServiceReference.PhoneAppSoap)(this)).ValidateDrugsAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.PhoneAppSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.PhoneAppSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.PhoneAppSoap))
            {
                return new System.ServiceModel.EndpointAddress("https://developmenttesting.clinisafesandbox.com/webservices/phoneapp.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.PhoneAppSoap12))
            {
                return new System.ServiceModel.EndpointAddress("https://developmenttesting.clinisafesandbox.com/webservices/phoneapp.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            PhoneAppSoap,
            
            PhoneAppSoap12,
        }
    }
}
